/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:b8c5a86c-d039-4828-9b45-065399661694",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_4BBgQJs3c",
    "aws_user_pools_web_client_id": "4ut10lbpo25v1oimrrh8ued7o0",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://coghqgzfmff43fzyuf6vl5qo5q.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-lv2p7qompbgyhbdyandkufawt4"
};


export default awsmobile;
